## @addtogroup functions
## @{
## @file
## @brief Configure Dart 2.x build_runner including files and Dart2JS options
## @}
targets:
  $default:
    sources:
      - "lib/**"
      - "node/**"
    builders:
      build_node_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            #- "--minify"
            - "--fast-startup"
