## @addtogroup functions
## @{
## @file
## @brief Configure Dart metadata and package dependencies
## @}
name: makerlabs_acm_functions
description: ACM Serverless Functions with a Flatbuffers API and connecting to Google APIs
version: 0.0.1
author: Paul Reimer <paul@p-rimes.net>

environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dependencies:
  googleapis: ^0.51.0
  googleapis_auth: ^0.2.5
  flat_buffers: ^1.9.2
  js: ^0.6.0
  node_http: ^1.0.0-dev.7.0
  node_io: ^1.0.0-dev.8.0
  node_interop: ^1.0.0-dev.8.0
  firebase_functions_interop: ^1.0.0-dev.4.0

dev_dependencies:
  test: ^1.0.0
  build_node_compilers: ^0.1.8
  build_runner: any
  build_test: any
