/**
@addtogroup electrical
@{

@file
@brief Documentation metadata for config files in this directory

@file electrical/bom.ini
@brief KiBoM custom schematic field mapping and CSV output settings file

@file electrical/makerlabs-acm-reader-lock_v1.0.0-cache.lib
@brief KiCad cached schematic library file

@file electrical/makerlabs-acm-reader-lock_v1.0.0.kicad_pcb
@brief KiCad board file -- layout and traces and 3D view

@file electrical/makerlabs-acm-reader-lock_v1.0.0.net
@brief KiCad schematic -> Board symbol to trace mapping

@file electrical/makerlabs-acm-reader-lock_v1.0.0.pro
@brief KiCad project file

@file electrical/makerlabs-acm-reader-lock_v1.0.0.sch
@brief KiCad Schematic file

@file electrical/makerlabs-acm-reader-lock_v1.0.0_BOM.csv
@brief KiCad Bill-of-Material (BOM), generated by KiBoM in CSV format

@file electrical/makerlabs-acm-reader-lock_v1.0.1_pcb_bottom.png
@brief PCB bottom layer image

@file electrical/makerlabs-acm-reader-lock_v1.0.1_pcb_top.png
@brief PCB top layer image

@file electrical/makerlabs-acm-reader-lock_v1.0.1_schematic.png
@brief PCB schematic image

@file electrical/makerlabs-acm-reader-lock_v1.0.xml
@brief KiCad PCB schematic / BOM info file

@file electrical/sym-lib-table
@brief KiCad schematic library file mapping

@dir electrical/gerbers
@brief Generated Gerber files sent to Seeedstudio PCB Fusion

@dir electrical/parts
@brief Custom KiCad libraries and footprints for parts used in this project.

@}
*/
